from setuptools import setup
setup(
  name = 'murphy',
  packages = ['murphy'],
  version = '0.5',
  license='MIT',
  description = 'Murphy is a powerful processor that is used to analyze a ton of twitter data from the internet archive.',
  long_description="""# Murphy\n\n* Murphy is a powerful processor that is used to analyze a ton of twitter data from the internet archive""",
  long_description_content_type="text/markdown",
  author = 'Ali Abbas',
  author_email = 'v2thegreat@gmail.com',
  url = 'https://github.com/Social-Media-Public-Analysis/murphy',
  download_url = 'https://github.com/Social-Media-Public-Analysis/murphy/archive/v_05.tar.gz',
  keywords = ['DASK', 'BIG DATA', 'MACHINE LEARNING'],
  install_requires=[
            'tqdm',
            'numpy',
            'pandas',
            'dask[complete]',
            'nltk',
            'pytest',
            'pyfiglet',
      ],
  classifiers=[
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.6',
  ],
)