from setuptools import setup
setup(
  name = 'smpamorpheus',
  packages = ['smpamorpheus'],
  version = '0.3',
  license='MIT',
  description = 'Morpheus is a powerful processor that is used to analyze a ton of twitter data from the internet archive.',
  long_description='README.md',
  long_description_content_type="text/markdown",
  author = 'Ali Abbas',
  author_email = 'v2thegreat@gmail.com',
  url = 'https://github.com/Social-Media-Public-Analysis/smpamorpheus',
  download_url = 'https://github.com/Social-Media-Public-Analysis/smpamorpheus/archive/v_03.tar.gz',
  keywords = ['DASK', 'BIG DATA', 'MACHINE LEARNING'],
  install_requires=[
            'tqdm',
            'numpy',
            'pandas',
            'dask[complete]',
            'nltk',
            'pytest',
            'pyfiglet',
      ],
  classifiers=[
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.6',
  ],
)